package postgres

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/integraltech/brainsentry/internal/domain"
	"github.com/integraltech/brainsentry/pkg/tenant"
)

// NoteRepository handles note persistence in PostgreSQL.
type NoteRepository struct {
	pool *pgxpool.Pool
}

// NewNoteRepository creates a new NoteRepository.
func NewNoteRepository(pool *pgxpool.Pool) *NoteRepository {
	return &NoteRepository{pool: pool}
}

// CreateNote creates a new note.
func (r *NoteRepository) CreateNote(ctx context.Context, n *domain.Note) error {
	if n.ID == "" {
		n.ID = uuid.New().String()
	}
	if n.TenantID == "" {
		n.TenantID = tenant.FromContext(ctx)
	}
	n.CreatedAt = time.Now()

	query := `INSERT INTO notes (id, tenant_id, session_id, type, title, content,
		category, project_id, severity, error_pattern, created_at, access_count, created_by, auto_generated)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`

	_, err := r.pool.Exec(ctx, query,
		n.ID, n.TenantID, n.SessionID, n.Type, n.Title, n.Content,
		n.Category, n.ProjectID, n.Severity, n.ErrorPattern, n.CreatedAt,
		n.AccessCount, n.CreatedBy, n.AutoGenerated,
	)
	if err != nil {
		return fmt.Errorf("creating note: %w", err)
	}

	// Save keywords
	for _, kw := range n.Keywords {
		if _, err := r.pool.Exec(ctx, `INSERT INTO note_keywords (note_id, keyword) VALUES ($1, $2) ON CONFLICT DO NOTHING`, n.ID, kw); err != nil {
			return fmt.Errorf("saving note keyword: %w", err)
		}
	}

	// Save related memories
	for _, mid := range n.RelatedMemoryIDs {
		if _, err := r.pool.Exec(ctx, `INSERT INTO note_related_memories (note_id, memory_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`, n.ID, mid); err != nil {
			return fmt.Errorf("saving note related memory: %w", err)
		}
	}

	return nil
}

// CreateHindsightNote creates a new hindsight note.
func (r *NoteRepository) CreateHindsightNote(ctx context.Context, n *domain.HindsightNote) error {
	if n.ID == "" {
		n.ID = uuid.New().String()
	}
	if n.TenantID == "" {
		n.TenantID = tenant.FromContext(ctx)
	}
	now := time.Now()
	n.CreatedAt = now
	n.UpdatedAt = now

	query := `INSERT INTO hindsight_notes (id, tenant_id, session_id, title, error_pattern, severity,
		access_count, error_type, error_message, error_context, resolution, resolution_steps,
		resolution_reference, lessons_learned, prevention_strategy, occurrence_count, reference_count,
		prevention_success_count, created_by, auto_generated, created_at, updated_at, prevention_verified, priority)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)`

	_, err := r.pool.Exec(ctx, query,
		n.ID, n.TenantID, n.SessionID, n.Title, n.ErrorPattern, n.Severity,
		n.AccessCount, n.ErrorType, n.ErrorMessage, n.ErrorContext,
		n.Resolution, n.ResolutionSteps, n.ResolutionReference,
		n.LessonsLearned, n.PreventionStrategy,
		n.OccurrenceCount, n.ReferenceCount, n.PreventionSuccessCount,
		n.CreatedBy, n.AutoGenerated, n.CreatedAt, n.UpdatedAt, n.PreventionVerified, n.Priority,
	)
	if err != nil {
		return fmt.Errorf("creating hindsight note: %w", err)
	}

	// Save tags
	for _, tag := range n.Tags {
		if _, err := r.pool.Exec(ctx, `INSERT INTO hindsight_tags (hindsight_note_id, tag) VALUES ($1, $2) ON CONFLICT DO NOTHING`, n.ID, tag); err != nil {
			return fmt.Errorf("saving hindsight tag: %w", err)
		}
	}

	// Save related memories
	for _, mid := range n.RelatedMemoryIDs {
		if _, err := r.pool.Exec(ctx, `INSERT INTO hindsight_related_memories (hindsight_note_id, memory_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`, n.ID, mid); err != nil {
			return fmt.Errorf("saving hindsight related memory: %w", err)
		}
	}

	return nil
}

// FindNotesBySession returns notes for a session.
func (r *NoteRepository) FindNotesBySession(ctx context.Context, sessionID string, limit int) ([]domain.Note, error) {
	tenantID := tenant.FromContext(ctx)

	query := `SELECT id, tenant_id, session_id, type, title, content, category,
		project_id, severity, error_pattern, created_at, last_accessed_at,
		last_occurrence_at, access_count, created_by, auto_generated
		FROM notes WHERE tenant_id = $1 AND session_id = $2
		ORDER BY created_at DESC LIMIT $3`

	rows, err := r.pool.Query(ctx, query, tenantID, sessionID, limit)
	if err != nil {
		return nil, fmt.Errorf("finding notes by session: %w", err)
	}
	defer rows.Close()

	var notes []domain.Note
	for rows.Next() {
		var n domain.Note
		if err := rows.Scan(
			&n.ID, &n.TenantID, &n.SessionID, &n.Type, &n.Title, &n.Content,
			&n.Category, &n.ProjectID, &n.Severity, &n.ErrorPattern, &n.CreatedAt,
			&n.LastAccessedAt, &n.LastOccurrenceAt, &n.AccessCount, &n.CreatedBy, &n.AutoGenerated,
		); err != nil {
			return nil, fmt.Errorf("scanning note: %w", err)
		}
		notes = append(notes, n)
	}
	return notes, nil
}

// ListNotes returns notes for the current tenant.
func (r *NoteRepository) ListNotes(ctx context.Context, limit int) ([]domain.Note, error) {
	tenantID := tenant.FromContext(ctx)

	query := `SELECT id, tenant_id, session_id, type, title, content, category,
		project_id, severity, error_pattern, created_at, last_accessed_at,
		last_occurrence_at, access_count, created_by, auto_generated
		FROM notes WHERE tenant_id = $1
		ORDER BY created_at DESC LIMIT $2`

	rows, err := r.pool.Query(ctx, query, tenantID, limit)
	if err != nil {
		return nil, fmt.Errorf("listing notes: %w", err)
	}
	defer rows.Close()

	var notes []domain.Note
	for rows.Next() {
		var n domain.Note
		if err := rows.Scan(
			&n.ID, &n.TenantID, &n.SessionID, &n.Type, &n.Title, &n.Content,
			&n.Category, &n.ProjectID, &n.Severity, &n.ErrorPattern, &n.CreatedAt,
			&n.LastAccessedAt, &n.LastOccurrenceAt, &n.AccessCount, &n.CreatedBy, &n.AutoGenerated,
		); err != nil {
			return nil, fmt.Errorf("scanning note: %w", err)
		}
		notes = append(notes, n)
	}
	return notes, nil
}

// ListHindsightNotes returns hindsight notes for the current tenant.
func (r *NoteRepository) ListHindsightNotes(ctx context.Context, limit int) ([]domain.HindsightNote, error) {
	tenantID := tenant.FromContext(ctx)

	query := `SELECT id, tenant_id, session_id, title, error_pattern, severity,
		last_accessed_at, access_count, error_type, error_message, error_context,
		resolution, resolution_steps, resolution_reference, lessons_learned,
		prevention_strategy, occurrence_count, reference_count, prevention_success_count,
		created_by, auto_generated, created_at, updated_at, last_occurrence_at,
		prevention_verified, priority
		FROM hindsight_notes WHERE tenant_id = $1
		ORDER BY occurrence_count DESC, created_at DESC LIMIT $2`

	rows, err := r.pool.Query(ctx, query, tenantID, limit)
	if err != nil {
		return nil, fmt.Errorf("listing hindsight notes: %w", err)
	}
	defer rows.Close()

	return r.scanHindsightRows(rows)
}

// FindHindsightBySession returns hindsight notes for a session.
func (r *NoteRepository) FindHindsightBySession(ctx context.Context, sessionID string, limit int) ([]domain.HindsightNote, error) {
	tenantID := tenant.FromContext(ctx)

	query := `SELECT id, tenant_id, session_id, title, error_pattern, severity,
		last_accessed_at, access_count, error_type, error_message, error_context,
		resolution, resolution_steps, resolution_reference, lessons_learned,
		prevention_strategy, occurrence_count, reference_count, prevention_success_count,
		created_by, auto_generated, created_at, updated_at, last_occurrence_at,
		prevention_verified, priority
		FROM hindsight_notes WHERE tenant_id = $1 AND session_id = $2
		ORDER BY created_at DESC LIMIT $3`

	rows, err := r.pool.Query(ctx, query, tenantID, sessionID, limit)
	if err != nil {
		return nil, fmt.Errorf("finding hindsight by session: %w", err)
	}
	defer rows.Close()

	return r.scanHindsightRows(rows)
}

// SearchHindsightNotes searches hindsight notes matching a prompt.
func (r *NoteRepository) SearchHindsightNotes(ctx context.Context, prompt, tenantID string, limit int) ([]domain.HindsightNote, error) {
	if tenantID == "" {
		tenantID = tenant.FromContext(ctx)
	}
	searchPattern := "%" + strings.ToLower(prompt) + "%"

	query := `SELECT id, tenant_id, session_id, title, error_pattern, severity,
		last_accessed_at, access_count, error_type, error_message, error_context,
		resolution, resolution_steps, resolution_reference, lessons_learned,
		prevention_strategy, occurrence_count, reference_count, prevention_success_count,
		created_by, auto_generated, created_at, updated_at, last_occurrence_at,
		prevention_verified, priority
		FROM hindsight_notes
		WHERE tenant_id = $1
		AND (LOWER(error_message) LIKE $2 OR LOWER(title) LIKE $2 OR LOWER(error_type) LIKE $2)
		ORDER BY occurrence_count DESC, created_at DESC
		LIMIT $3`

	rows, err := r.pool.Query(ctx, query, tenantID, searchPattern, limit)
	if err != nil {
		return nil, fmt.Errorf("searching hindsight notes: %w", err)
	}
	defer rows.Close()

	return r.scanHindsightRows(rows)
}

// GetRelevantNotes returns relevant hindsight notes for a tenant.
func (r *NoteRepository) GetRelevantNotes(ctx context.Context, tenantID string, limit int) ([]domain.HindsightNote, error) {
	if tenantID == "" {
		tenantID = tenant.FromContext(ctx)
	}

	query := `SELECT id, tenant_id, session_id, title, error_pattern, severity,
		last_accessed_at, access_count, error_type, error_message, error_context,
		resolution, resolution_steps, resolution_reference, lessons_learned,
		prevention_strategy, occurrence_count, reference_count, prevention_success_count,
		created_by, auto_generated, created_at, updated_at, last_occurrence_at,
		prevention_verified, priority
		FROM hindsight_notes
		WHERE tenant_id = $1
		ORDER BY occurrence_count DESC, created_at DESC
		LIMIT $2`

	rows, err := r.pool.Query(ctx, query, tenantID, limit)
	if err != nil {
		return nil, fmt.Errorf("getting relevant notes: %w", err)
	}
	defer rows.Close()

	return r.scanHindsightRows(rows)
}

// IncrementOccurrence increments the occurrence count for a hindsight note.
func (r *NoteRepository) IncrementOccurrence(ctx context.Context, id string) error {
	_, err := r.pool.Exec(ctx,
		`UPDATE hindsight_notes SET occurrence_count = occurrence_count + 1, last_occurrence_at = $2, updated_at = $2 WHERE id = $1`,
		id, time.Now())
	return err
}

func (r *NoteRepository) scanHindsightRows(rows interface{ Next() bool; Scan(...any) error }) ([]domain.HindsightNote, error) {
	var notes []domain.HindsightNote
	for rows.Next() {
		var n domain.HindsightNote
		if err := rows.Scan(
			&n.ID, &n.TenantID, &n.SessionID, &n.Title, &n.ErrorPattern, &n.Severity,
			&n.LastAccessedAt, &n.AccessCount, &n.ErrorType, &n.ErrorMessage, &n.ErrorContext,
			&n.Resolution, &n.ResolutionSteps, &n.ResolutionReference, &n.LessonsLearned,
			&n.PreventionStrategy, &n.OccurrenceCount, &n.ReferenceCount, &n.PreventionSuccessCount,
			&n.CreatedBy, &n.AutoGenerated, &n.CreatedAt, &n.UpdatedAt, &n.LastOccurrenceAt,
			&n.PreventionVerified, &n.Priority,
		); err != nil {
			return nil, fmt.Errorf("scanning hindsight note: %w", err)
		}
		notes = append(notes, n)
	}
	return notes, nil
}
