#!/usr/bin/env bash
# build-llms.sh — generate llms-full.txt by inlining the docs referenced in
# llms.txt. Lets an agent fetch a single URL and have everything it needs.
#
# Usage: ./scripts/build-llms.sh
# Output: llms-full.txt at repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="llms-full.txt"
SRC="llms.txt"

if [ ! -f "$SRC" ]; then
  echo "error: $SRC not found at repo root" >&2
  exit 1
fi

{
  echo "# brainsentry.io — full doc bundle"
  echo
  echo "> Generated by scripts/build-llms.sh from llms.txt. Each section below"
  echo "> is the inlined content of one referenced file. Updated:"
  echo "> $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  cat "$SRC"
  echo
  echo "---"
  echo
  echo "# Inlined documents"
  echo

  grep -oE '\([^)]+\.(md|go|tsx|ts)\)' "$SRC" \
    | sed -E 's/^\((.*)\)$/\1/' \
    | grep -v '^https\?://' \
    | sort -u \
    | while read -r path; do
        if [ -f "$path" ]; then
          echo
          echo "## $path"
          echo
          echo '```'
          cat "$path"
          echo '```'
          echo
        else
          echo "<!-- WARN: $path referenced in llms.txt but not found -->"
        fi
      done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
