package commands

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/integraltech/brainsentry/internal/store"
	"github.com/spf13/cobra"
)

// InitOptions controls the `brainsentry init` flow.
type InitOptions struct {
	Embedded bool
	Path     string
	Writer   io.Writer
}

func newInitCmd(_ *App) *cobra.Command {
	opts := &InitOptions{Writer: os.Stdout}
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Bootstrap a brainsentry workspace (embedded zero-config or full Postgres)",
		Long: `init creates the local files brainsentry needs to run.

With --embedded (recommended for development and demos):
  - Creates ~/.brainsentry/brain.db.json (a JSON-backed embedded store)
  - Writes ~/.brainsentry/config.yaml pointing at the embedded backend
  - No Postgres, no Redis, no FalkorDB required

With --path to override location, and without --embedded, the command
just prints the recommended config skeleton — actually creating Postgres
schemas remains the responsibility of the standard 'go run ./cmd/server
--migrate-only' path.`,
		RunE: func(c *cobra.Command, _ []string) error {
			home, err := os.UserHomeDir()
			if err != nil {
				return err
			}
			base := opts.Path
			if base == "" {
				base = filepath.Join(home, ".brainsentry")
			}
			if err := os.MkdirAll(base, 0o755); err != nil {
				return err
			}

			if opts.Embedded {
				dbPath := filepath.Join(base, "brain.db.json")
				s, err := store.OpenEmbedded(dbPath)
				if err != nil {
					return fmt.Errorf("open embedded store: %w", err)
				}
				_ = s.Close()

				cfgPath := filepath.Join(base, "config.yaml")
				if err := writeEmbeddedConfig(cfgPath, dbPath); err != nil {
					return err
				}
				fmt.Fprintf(opts.Writer, "embedded workspace ready\n")
				fmt.Fprintf(opts.Writer, "  store:  %s\n", dbPath)
				fmt.Fprintf(opts.Writer, "  config: %s\n", cfgPath)
				fmt.Fprintln(opts.Writer)
				fmt.Fprintln(opts.Writer, "next steps:")
				fmt.Fprintln(opts.Writer, "  brainsentry add 'first memory'         # create a memory")
				fmt.Fprintln(opts.Writer, "  brainsentry list                       # see what's stored")
				fmt.Fprintln(opts.Writer, "  brainsentry search 'first'             # text search")
				return nil
			}

			fmt.Fprintln(opts.Writer, "for a full Postgres workspace, see INSTALL_FOR_AGENTS.md.")
			fmt.Fprintln(opts.Writer, "for the zero-config embedded mode, re-run with: brainsentry init --embedded")
			return nil
		},
	}
	cmd.Flags().BoolVar(&opts.Embedded, "embedded", false, "create the embedded zero-config workspace")
	cmd.Flags().StringVar(&opts.Path, "path", "", "override the workspace directory (default ~/.brainsentry)")
	return cmd
}

// writeEmbeddedConfig writes a minimal config.yaml that points the server
// at the embedded store. We don't try to template every available knob —
// just enough to boot.
func writeEmbeddedConfig(cfgPath, dbPath string) error {
	body := `# brainsentry config — embedded zero-config mode
# Generated by 'brainsentry init --embedded'.
# Switch to Postgres later by editing this file (see config.yaml.example).

server:
  port: 8080
  context_path: ""

store:
  backend: embedded
  embedded:
    path: ` + quoteYAML(dbPath) + `

ai:
  provider: openrouter
  api_key: ${OPENROUTER_API_KEY}  # required for LLM features

embedding:
  model: openai/text-embedding-3-small
  dimensions: 384

models:
  default: ""           # falls back to ai.model
  tier:
    utility: openai/gpt-4o-mini
    reasoning: anthropic/claude-3-5-sonnet
    deep: anthropic/claude-opus-4
    subagent: anthropic/claude-3-5-sonnet
`
	return os.WriteFile(cfgPath, []byte(body), 0o600)
}

func quoteYAML(s string) string {
	// minimal YAML-safe single-quoting
	if s == "" {
		return `""`
	}
	out := []byte{'\''}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '\'' {
			out = append(out, '\'', '\'')
		} else {
			out = append(out, c)
		}
	}
	out = append(out, '\'')
	return string(out)
}
